name: Hacer Deploy

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    Deployar:
        runs-on: ubuntu-latest

        steps:
            - name: Iniciar deploy en Render
              run:  |
                curl -X POST "$RENDER_DEPLOY_HOOK"
              env:
                RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}